# detector.py — Dynamo AI
# In-house AI Text Detector + Plagiarism Checker
# Uses: Gemini (analysis & scoring), Tavily (web search), Semantic Scholar (academic)

import asyncio
import aiohttp
import json
import re
from google import genai
import config

_client = genai.Client(api_key=config.GEMINI_KEY) if config.GEMINI_KEY else None

# ─────────────────────────────────────────────────────────────────────────────
# AI DETECTOR
# ─────────────────────────────────────────────────────────────────────────────

_AI_PROMPT = """\
You are a forensic linguist and expert AI text detector.

Analyze the following text and determine whether it was written by a human or generated by an AI (ChatGPT, Gemini, Claude, etc.).

Common AI writing patterns to look for:
- Formulaic transitions: "Furthermore", "Moreover", "In conclusion", "It is worth noting", "It is important to"
- Perfectly balanced, symmetrical paragraphs with no natural irregularity
- Comprehensive hedging — avoids strong opinions, covers every angle
- Unnaturally clean grammar, consistent rhythm throughout
- Generic observations that could apply to any context
- Overuse of bullet points and structured lists
- No typos, colloquial language, personal voice, or emotional investment
- Repetitive sentence structure across paragraphs

Common human writing patterns:
- Personal opinions, emotions, and idiosyncratic word choices
- Occasional typos, informal phrasing, or conversational asides
- Uneven paragraph lengths and abrupt transitions
- Specific personal experiences or non-generic examples
- Strong or opinionated statements without hedging

Return ONLY a valid JSON object with this exact structure:
{
  "score": <integer 0-100; 0=definitely human, 100=definitely AI>,
  "label": "<exactly one of: Human Written | Likely Human | Mixed | Likely AI | AI Generated>",
  "confidence": "<Low|Medium|High>",
  "signals": [<list of 3-5 short specific evidence strings found in the actual text>],
  "summary": "<2-3 sentences plain English verdict>"
}

TEXT TO ANALYZE:
"""


async def detect_ai(text: str) -> dict:
    if not _client:
        return _err("AI detector not available — Gemini not configured.")
    loop = asyncio.get_event_loop()
    try:
        resp = await loop.run_in_executor(
            None,
            lambda: _client.models.generate_content(
                model="gemini-3-flash-preview",
                contents=_AI_PROMPT + text[:4000],
            )
        )
        match = re.search(r'\{.*\}', resp.text.strip(), re.DOTALL)
        if match:
            return json.loads(match.group())
    except Exception as e:
        print(f"[Detector] AI detection error: {e}")
    return _err("Analysis failed. Please try again.")


def _err(msg: str) -> dict:
    return {
        "score": 50, "label": "Mixed", "confidence": "Low",
        "signals": [msg], "summary": msg,
    }


# ─────────────────────────────────────────────────────────────────────────────
# PLAGIARISM CHECKER
# ─────────────────────────────────────────────────────────────────────────────

async def check_plagiarism(text: str) -> dict:
    """Check originality using Tavily web search + Semantic Scholar + Gemini scoring."""
    query   = text[:250].strip()
    sources = []

    # 1. Tavily web search for matching online content
    try:
        from tavily import TavilyClient
        if config.TAVILY_KEY:
            tc = TavilyClient(api_key=config.TAVILY_KEY)
            r  = tc.search(query=query[:350], search_depth="advanced", max_results=6)
            for item in r.get("results", []):
                if item.get("url"):
                    sources.append({
                        "source":  (item.get("title") or "Unknown")[:80],
                        "url":     item.get("url", ""),
                        "type":    "web",
                        "snippet": (item.get("content") or "")[:200],
                    })
    except Exception as e:
        print(f"[Plagiarism] Tavily error: {e}")

    # 2. Semantic Scholar for academic paper matches
    try:
        async with aiohttp.ClientSession() as session:
            params = {
                "query":  query[:200],
                "fields": "title,year,authors,externalIds,abstract",
                "limit":  5,
            }
            async with session.get(
                "https://api.semanticscholar.org/graph/v1/paper/search",
                params=params,
                headers={"User-Agent": "DynamoAI/1.0"},
                timeout=aiohttp.ClientTimeout(total=10),
            ) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    for p in data.get("data", []):
                        if p.get("title"):
                            doi = (p.get("externalIds") or {}).get("DOI", "")
                            sources.append({
                                "source":  p["title"][:80],
                                "url":     f"https://doi.org/{doi}" if doi else "",
                                "type":    "academic",
                                "snippet": (p.get("abstract") or f"Published {p.get('year', 'N/A')}")[:200],
                            })
    except Exception as e:
        print(f"[Plagiarism] Semantic Scholar error: {e}")

    # 3. Gemini scores similarity against found sources
    score   = 0
    summary = "No closely matching sources found online. The text appears to be original."

    if sources and _client:
        src_block = "\n".join(
            f"- [{s['type'].upper()}] {s['source']}: {s['snippet']}"
            for s in sources[:6]
        )
        prompt = (
            "You are a plagiarism detection expert.\n\n"
            f"Submitted text (first 600 chars):\n\"{text[:600]}\"\n\n"
            f"Potential matching sources found online:\n{src_block}\n\n"
            "Based on the content overlap between the submitted text and these sources, "
            "provide an originality assessment.\n"
            "Return ONLY valid JSON: "
            "{\"score\": <int 0-100; 0=fully original, 100=directly plagiarized>, "
            "\"summary\": \"<2-3 sentence plain-English assessment>\"}"
        )
        loop = asyncio.get_event_loop()
        try:
            resp = await loop.run_in_executor(
                None,
                lambda: _client.models.generate_content(
                    model="gemini-3-flash-preview",
                    contents=prompt,
                )
            )
            match = re.search(r'\{.*\}', resp.text.strip(), re.DOTALL)
            if match:
                parsed  = json.loads(match.group())
                score   = max(0, min(100, int(parsed.get("score", 0))))
                summary = parsed.get("summary", summary)
        except Exception as e:
            print(f"[Plagiarism] Gemini scoring error: {e}")

    if score > 65:
        label = "High Risk"
    elif score > 35:
        label = "Moderate Risk"
    else:
        label = "Low Risk — Original"

    return {
        "score":   score,
        "label":   label,
        "summary": summary,
        "sources": sources[:8],
    }
