# presentation_engine.py — Dynamo AI (FINAL)
# Builds real PPT from AI JSON schema

import io
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from fastapi.responses import StreamingResponse

# --------------------------------------------------
# THEMES
# --------------------------------------------------

THEMES = {
    "light": {
        "bg": None,
        "title_size": 40,
        "body_size": 20
    },
    "dark": {
        "bg": None,
        "title_size": 40,
        "body_size": 20
    },
    "executive": {
        "bg": None,
        "title_size": 44,
        "body_size": 22
    }
}

# --------------------------------------------------
# PRESENTATION BUILDER
# --------------------------------------------------

def build_presentation(payload: dict):
    """
    Expected payload:
    {
      "title": "Topic",
      "theme": "executive",
      "slides": [
        {
          "type": "content",
          "heading": "...",
          "bullets": [...]
        },
        {
          "type": "chart",
          "heading": "...",
          "chart": {
            "kind": "bar",
            "labels": [],
            "values": []
          }
        }
      ]
    }
    """

    prs = Presentation()
    theme = payload.get("theme", "light")
    style = THEMES.get(theme, THEMES["light"])

    # -------------------------
    # TITLE SLIDE
    # -------------------------
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = payload.get("title", "Dynamo AI Presentation")
    slide.placeholders[1].text = "Generated by Dynamo AI"

    # -------------------------
    # CONTENT SLIDES
    # -------------------------
    for s in payload.get("slides", []):
        if s.get("type") == "content":
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = s.get("heading", "")

            body = slide.placeholders[1].text_frame
            body.clear()

            for bullet in s.get("bullets", []):
                p = body.add_paragraph()
                p.text = bullet
                p.font.size = Pt(style["body_size"])
                p.level = 1

        elif s.get("type") == "chart":
            slide = prs.slides.add_slide(prs.slide_layouts[5])
            slide.shapes.title.text = s.get("heading", "")

            chart_info = s.get("chart", {})
            labels = chart_info.get("labels", [])
            values = chart_info.get("values", [])

            chart_data = ChartData()
            chart_data.categories = labels
            chart_data.add_series("Series", values)

            slide.shapes.add_chart(
                XL_CHART_TYPE.COLUMN_CLUSTERED,
                Inches(1),
                Inches(1.5),
                Inches(8),
                Inches(4),
                chart_data
            )

    # -------------------------
    # STREAM RESPONSE
    # -------------------------
    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={
            "Content-Disposition": "attachment; filename=DynamoAI_Presentation.pptx"
        }
    )
