// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar-scroll/CollapsibleFolders.tsx": () => import("../components/mockups/sidebar-scroll/CollapsibleFolders.tsx"),
  "./components/mockups/sidebar-scroll/StickyZones.tsx": () => import("../components/mockups/sidebar-scroll/StickyZones.tsx"),
  "./components/mockups/sidebar-scroll/TabSwitcher.tsx": () => import("../components/mockups/sidebar-scroll/TabSwitcher.tsx")
};
