import { useState } from "react";

const SLIDES = [
  {
    type: "title",
    heading: "CRISPR Gene Editing in Rare Disease Treatment",
    subheading: "A Phase II Clinical Review",
    body: null,
    tag: "Title Slide",
    layout: "title",
  },
  {
    type: "thesis",
    heading: "Research Question",
    body: "Can targeted CRISPR-Cas9 edits reduce disease burden in patients with monogenic rare diseases by 40–60% within 18 months of a single treatment?",
    note: "Central hypothesis — drives all subsequent evidence",
    tag: "Thesis",
    layout: "callout",
  },
  {
    type: "evidence",
    heading: "Phase II Clinical Trial Results",
    bullets: [
      "n = 142 patients across 3 cohorts (ages 8–45)",
      "52% mean symptom reduction (p < 0.001)",
      "18-month follow-up — durable response in 87% of cases",
      "No serious adverse events attributed to off-target edits",
    ],
    citation: "Smith et al. (2024). Nature Medicine, 30(4), 882–891.",
    tag: "Evidence",
    layout: "bullets",
  },
  {
    type: "chart",
    heading: "Efficacy vs. Control Group",
    body: "Chart: CRISPR vs. standard of care — symptom reduction at 6, 12, 18 months",
    tag: "Chart",
    layout: "chart",
  },
  {
    type: "comparison",
    heading: "CRISPR vs. Existing Gene Therapies",
    left: { label: "CRISPR-Cas9", points: ["High precision", "Single treatment", "Low off-target risk", "Cost: $80k–120k"] },
    right: { label: "AAV Gene Therapy", points: ["Limited payload", "Repeat dosing", "Immune response risk", "Cost: $200k–400k"] },
    tag: "Comparison",
    layout: "comparison",
  },
  {
    type: "conclusion",
    heading: "Implications & Next Steps",
    bullets: [
      "Phase III trial targeting 400+ patients — begin Q3 2025",
      "FDA Breakthrough Therapy Designation application in progress",
      "Estimated regulatory approval window: 2027–2028",
    ],
    tag: "Conclusion",
    layout: "conclusion",
  },
];

function SlideContent({ slide }: { slide: typeof SLIDES[0] }) {
  if (slide.layout === "title") {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-6">
        <div className="w-10 h-1 bg-yellow-400 rounded-full mb-4" />
        <h1 className="text-2xl font-black text-white leading-tight mb-3">{slide.heading}</h1>
        {slide.subheading && <p className="text-slate-400 text-sm">{slide.subheading}</p>}
        <div className="mt-6 text-[10px] text-slate-500 uppercase tracking-widest">Generated by Dynamo AI · Academic Style</div>
      </div>
    );
  }

  if (slide.layout === "callout") {
    return (
      <div className="flex flex-col justify-center h-full px-5">
        <div className="text-[10px] font-bold uppercase tracking-widest text-yellow-400 mb-2">{slide.tag}</div>
        <h2 className="text-lg font-black text-white mb-4 leading-snug">{slide.heading}</h2>
        <div className="bg-white/10 border border-white/20 rounded-xl p-4">
          <p className="text-sm text-slate-200 leading-relaxed italic">"{slide.body}"</p>
        </div>
        {slide.note && <p className="text-[10px] text-slate-500 mt-3">↑ {slide.note}</p>}
      </div>
    );
  }

  if (slide.layout === "bullets") {
    return (
      <div className="flex flex-col justify-center h-full px-5">
        <div className="text-[10px] font-bold uppercase tracking-widest text-yellow-400 mb-2">{slide.tag}</div>
        <h2 className="text-base font-black text-white mb-3">{slide.heading}</h2>
        <ul className="space-y-2 mb-3">
          {(slide as any).bullets?.map((b: string, i: number) => (
            <li key={i} className="flex items-start gap-2 text-xs text-slate-300">
              <span className="w-1.5 h-1.5 bg-yellow-400 rounded-full mt-1.5 flex-shrink-0" />
              {b}
            </li>
          ))}
        </ul>
        {(slide as any).citation && (
          <div className="text-[9px] text-slate-500 border-t border-white/10 pt-2 italic">
            📚 {(slide as any).citation}
          </div>
        )}
      </div>
    );
  }

  if (slide.layout === "chart") {
    const bars = [45, 72, 87, 31, 52, 61];
    return (
      <div className="flex flex-col justify-center h-full px-5">
        <div className="text-[10px] font-bold uppercase tracking-widest text-yellow-400 mb-2">{slide.tag}</div>
        <h2 className="text-base font-black text-white mb-3">{slide.heading}</h2>
        <div className="flex items-end gap-2 h-24 mb-2">
          {["6m CRISPR","6m Control","12m CRISPR","12m Control","18m CRISPR","18m Control"].map((lbl, i) => (
            <div key={i} className="flex flex-col items-center flex-1 gap-1">
              <div
                className={`w-full rounded-t-md ${i % 2 === 0 ? "bg-yellow-400" : "bg-slate-600"}`}
                style={{ height: `${bars[i]}%` }}
              />
              <span className="text-[7px] text-slate-400 text-center leading-tight">{lbl}</span>
            </div>
          ))}
        </div>
        <div className="flex gap-3 text-[9px] text-slate-400">
          <span className="flex items-center gap-1"><span className="w-2 h-2 bg-yellow-400 rounded-sm inline-block"/>CRISPR group</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 bg-slate-600 rounded-sm inline-block"/>Control group</span>
        </div>
      </div>
    );
  }

  if (slide.layout === "comparison") {
    const s = slide as any;
    return (
      <div className="flex flex-col justify-center h-full px-5">
        <div className="text-[10px] font-bold uppercase tracking-widest text-yellow-400 mb-2">{slide.tag}</div>
        <h2 className="text-base font-black text-white mb-3">{slide.heading}</h2>
        <div className="grid grid-cols-2 gap-3">
          {[s.left, s.right].map((col: any, ci: number) => (
            <div key={ci} className={`rounded-xl p-3 ${ci === 0 ? "bg-yellow-400/10 border border-yellow-400/30" : "bg-white/5 border border-white/10"}`}>
              <div className={`text-[10px] font-bold mb-2 ${ci === 0 ? "text-yellow-400" : "text-slate-400"}`}>{col.label}</div>
              {col.points.map((p: string, pi: number) => (
                <div key={pi} className="text-[10px] text-slate-300 py-0.5 border-b border-white/5 last:border-0">{p}</div>
              ))}
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (slide.layout === "conclusion") {
    return (
      <div className="flex flex-col justify-center h-full px-5">
        <div className="text-[10px] font-bold uppercase tracking-widest text-yellow-400 mb-2">{slide.tag}</div>
        <h2 className="text-base font-black text-white mb-4">{slide.heading}</h2>
        <ul className="space-y-3">
          {(slide as any).bullets?.map((b: string, i: number) => (
            <li key={i} className="flex items-start gap-3 bg-white/5 rounded-lg px-3 py-2.5">
              <span className="text-yellow-400 font-black text-sm mt-0.5">{i + 1}</span>
              <span className="text-xs text-slate-200 leading-relaxed">{b}</span>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  return null;
}

export default function DeckPreview() {
  const [current, setCurrent] = useState(2);
  const slide = SLIDES[current];

  return (
    <div className="min-h-screen bg-gray-100 font-sans flex flex-col">

      {/* Top bar */}
      <div className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 bg-yellow-400 rounded-lg flex items-center justify-center text-xs">📊</div>
          <span className="text-xs font-bold text-gray-900">CRISPR Research Deck</span>
          <span className="text-[10px] text-gray-400">· Academic · {SLIDES.length} slides</span>
        </div>
        <div className="flex items-center gap-2">
          <button className="text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded-lg hover:bg-gray-100 transition">✏️ Edit</button>
          <button className="px-3 py-1.5 bg-slate-800 text-white text-xs font-bold rounded-lg hover:bg-slate-700 transition">
            ⬇ Export PPTX
          </button>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden" style={{ height: "calc(100vh - 56px)" }}>

        {/* Thumbnail strip */}
        <div className="w-20 bg-white border-r border-gray-200 flex flex-col gap-2 p-2 overflow-y-auto">
          {SLIDES.map((s, i) => (
            <button
              key={i}
              onClick={() => setCurrent(i)}
              className={`w-full aspect-video rounded-md border-2 flex items-center justify-center text-[8px] font-bold transition overflow-hidden ${
                i === current
                  ? "border-yellow-400 shadow-sm"
                  : "border-gray-200 hover:border-gray-300"
              } bg-slate-800`}>
              <span className="text-[8px] text-slate-400">{i + 1}</span>
            </button>
          ))}
        </div>

        {/* Main slide view */}
        <div className="flex-1 flex flex-col items-center justify-center p-4 bg-gray-100">
          <div
            className="w-full bg-slate-800 rounded-xl shadow-xl overflow-hidden"
            style={{ maxWidth: "520px", aspectRatio: "16/9", minHeight: "260px" }}>
            <SlideContent slide={slide} />
          </div>

          {/* Nav */}
          <div className="flex items-center gap-4 mt-4">
            <button
              onClick={() => setCurrent(c => Math.max(0, c - 1))}
              disabled={current === 0}
              className="px-3 py-1.5 bg-white text-gray-600 text-xs font-bold rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-40 transition">
              ← Prev
            </button>
            <span className="text-xs text-gray-500 font-semibold">{current + 1} / {SLIDES.length}</span>
            <button
              onClick={() => setCurrent(c => Math.min(SLIDES.length - 1, c + 1))}
              disabled={current === SLIDES.length - 1}
              className="px-3 py-1.5 bg-white text-gray-600 text-xs font-bold rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-40 transition">
              Next →
            </button>
          </div>
        </div>

        {/* Right panel */}
        <div className="w-44 bg-white border-l border-gray-200 p-3 flex flex-col gap-3">
          <div>
            <div className="text-[9px] font-bold uppercase tracking-widest text-gray-400 mb-2">Slide type</div>
            <span className="text-[10px] font-bold px-2 py-1 bg-blue-100 text-blue-700 rounded-full">{slide.tag}</span>
          </div>
          <div>
            <div className="text-[9px] font-bold uppercase tracking-widest text-gray-400 mb-2">Actions</div>
            <div className="space-y-1.5">
              <button className="w-full text-left text-[10px] text-gray-600 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition">🔄 Regenerate</button>
              <button className="w-full text-left text-[10px] text-gray-600 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition">✏️ Edit content</button>
              <button className="w-full text-left text-[10px] text-gray-600 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition">🔀 Swap layout</button>
              <button className="w-full text-left text-[10px] text-gray-600 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition">➕ Add after</button>
              <button className="w-full text-left text-[10px] text-red-400 px-2 py-1.5 rounded-lg hover:bg-red-50 transition">✕ Remove</button>
            </div>
          </div>
          <div>
            <div className="text-[9px] font-bold uppercase tracking-widest text-gray-400 mb-2">Export</div>
            <button className="w-full py-2 bg-slate-800 text-white text-[10px] font-bold rounded-lg hover:bg-slate-700 transition">
              ⬇ PPTX
            </button>
            <button className="w-full py-2 mt-1.5 border border-gray-200 text-gray-600 text-[10px] font-bold rounded-lg hover:bg-gray-50 transition">
              🔗 Share link
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
